runtime: python

env: flex

runtime_config:
  operating_system: "ubuntu22"
  runtime_version: "3.12"

entrypoint: python3 main.py

instance_class: F1

automatic_scaling:
  min_instances: 1
  max_instances: 1