runtime: python

env: flex

runtime_config:
  operating_system: "ubuntu22"
  runtime_version: "3.12"

entrypoint: python3 main.py

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

instance_class: F1

automatic_scaling:
  min_instances: 1
  max_instances: 1